# Generated by Django 5.0.4 on 2024-05-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unidade_de_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=16)),
                ('localizacao', models.CharField(max_length=50, verbose_name='Localização')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('empretimo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='emprestimos.emprestimo')),
            ],
        ),
    ]
