# Generated by Django 5.0.4 on 2024-05-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo_has_components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.componente')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimos.emprestimo')),
            ],
        ),
    ]
