# Generated by Django 5.0.4 on 2024-05-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='empretimo',
            new_name='emprestimo',
        ),
    ]
