# Generated by Django 5.0.4 on 2024-05-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
        ('inventario', '0002_emprestimo_has_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='empretimo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='emprestimos.emprestimo'),
        ),
    ]
