# Generated by Django 5.0.4 on 2024-05-21 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
        ('inventario', '0004_alter_equipamento_empretimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='empretimo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='emprestimos.emprestimo'),
        ),
    ]
