# Generated by Django 5.0.4 on 2024-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_equipamento_empretimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
