# Generated by Django 5.0.4 on 2024-06-06 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(max_length=50)),
                ('data_de_retirada', models.DateField(auto_now_add=True, verbose_name='Data de Retirada')),
                ('data_de_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacao.aluno')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacao.funcionario')),
            ],
        ),
    ]
