# Generated by Django 5.0.6 on 2024-05-31 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(max_length=50)),
                ('data_de_retirada', models.DateField(verbose_name='Data de Retirada')),
                ('data_de_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacao.aluno')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacao.funcionario')),
            ],
        ),
    ]
