# Generated by Django 5.0.4 on 2024-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_de_retirada',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Retirada'),
        ),
    ]
