# Generated by Django 5.0.4 on 2024-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_aluno_alter_emprestimo_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
