# Generated by Django 5.0.4 on 2024-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_alter_emprestimo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
